### ISSUE TITLE
support setting constraint priorities

### ISSUE THREAD

**Issue by jeremy-w** [indragiek/SwiftAutoLayout#1]
[robb/Cartography](https://github.com/robb/Cartography) (linked by iOS Dev Weekly) is using `~` for indicating priority, as in:

```swift
view.width  >= 200 ~ 100
```

**Comment by dhoerl** [comment]
I added the '!' operator to set priority in my [fork](https://github.com/dhoerl/SwiftAutoLayout)

**Comment by indragiek** [comment]
This is implemented in v1.0.0.
