### ISSUE TITLE
Support for layout guides

### ISSUE THREAD

**Issue by okla** [indragiek/SwiftAutoLayout#12]

**Comment by beloglazov** [comment]
:+1:

**Comment by dhoerl** [comment]
Assuming you mean add the constants for all the new iOS attributes (margins etc), then I did this in my [fork](https://github.com/dhoerl/SwiftAutoLayout). I plan to continue support of this masterful project!

**Comment by indragiek** [comment]
@dhoerl If you're interested in submitting a pull request I'd be happy to review and merge your changes :)

**Comment by dhoerl** [comment]
Your repository here looked abandoned - I have a hobby of resurrecting really great but unsupported code :-)

In any case, what I've done is only appropriate for Xcode 7 (that is, the unit tests use the new @testing feature, which allows most functions to not require 'public'. I'll do a pull request in the fall, when Xcode 7 goes official.

Or, if you are OK with the unit tests requiring Xcode 7, I can do the pull request now.

**Comment by indragiek** [comment]
@dhoerl I could merge it into a separate xcode7 branch until Xcode 7 goes public.

**Comment by indragiek** [comment]
This is implemented in v1.0.0.
