### ISSUE TITLE
How to implement a list of UIViews

### ISSUE THREAD

**Issue by sean-hill** [indragiek/SwiftAutoLayout#13]
Hey there, I'm curious to know if SwiftAutoLayout will accomplish my needs. I'd like to have a list of stacked UIView's that fill the width of the screen, each having a dynamic height, and each being seperated by 10 points apart from each other. AKA, something like Facebook's News Feed. Thanks!

**Comment by indragiek** [comment]
This very late response probably isn't useful anymore, but just in case: SwiftAutoLayout isn't a library that implements common layouts, just a more expressive syntax for building autolayout constraints (i.e. it's a lower level library). It sounds like you're looking for [UIStackView](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIStackView_Class_Reference/), which was introduced in iOS 9. If you're targeting earlier releases, there are some open source projects like [ORStackView](https://github.com/orta/ORStackView) that implement similar functionality.
