### ISSUE TITLE
Update / Remake Constraints

### ISSUE THREAD

**Issue by fabb** [indragiek/SwiftAutoLayout#6]
First off: awesome idea to use operator overloading for defining layout constraints.
There's one catch though - other autolayout frameworks provide methods to update / remove / remake layout constraints.
Like Masonry: https://github.com/Masonry/Masonry/blob/master/Masonry/View%2BMASAdditions.h#L68

How could we represent this with overloaded operators?
I guess removing constraints better would be an own method call. It could also be called before making new constraints to provide the same functionality as remake. That leaves update. Should update be the default behavior?

**Comment by indragiek** [comment]
While that is a useful piece of functionality, I think its beyond the scope of what SwiftAutoLayout was intended to be, which is simply a better syntax for creating constraints. How you manage those constraints is entirely up to you, and the library isn't mean to influence that.
